version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: fintrack-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: fintrack
    volumes:
      - mongo_data:/data/db
    networks:
      - fintrack-network

  backend:
    build:
      context: ./fintrack-be
    container_name: fintrack-backend
    restart: always
    environment:
      ENVIRONMENT: production
      MONGO_URL: mongodb://admin:admin123@mongo:27017/fintrack?authSource=admin
      DB_NAME: fintrack
    expose:
      - "8000"
    depends_on:
      - mongo
    networks:
      - fintrack-network

  frontend:
    build:
      context: ./internal-dashboard-fe
    container_name: fintrack-frontend
    restart: always
    expose:
      - "80"
    networks:
      - fintrack-network

  nginx:
    image: nginx:alpine
    container_name: fintrack-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - fintrack-network

volumes:
  mongo_data:

networks:
  fintrack-network:
    driver: bridge
